(deftheme light
  "Created 2016-02-28.")

(custom-theme-set-faces
 'light
 '(info-title-1 ((((class color) (min-colors 89)) (:family "helv" :weight bold :height 1.728))))
 '(info-title-2 ((((class color) (min-colors 89)) (:family "helv" :weight bold :height 1.44))))
 '(info-title-3 ((((class color) (min-colors 89)) (:family "helv" :weight bold :height 1.2))))
 '(info-title-4 ((((class color) (min-colors 89)) (:family "helv" :weight bold))))
 '(cursor ((t (:background "#80ffff"))))
 '(error ((t (:foreground "orange red"))))
 '(font-lock-builtin-face ((t (:foreground "#0000ff"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "lime green"))))
 '(font-lock-comment-face ((t (:foreground "lime green"))))
 '(font-lock-constant-face ((t (:foreground "#0000ff"))))
 '(font-lock-doc-face ((t (:foreground "lime green"))))
 '(font-lock-function-name-face ((t (:foreground "#6020ff"))))
 '(font-lock-keyword-face ((t (:foreground "#c040ff"))))
 '(font-lock-preprocessor-face ((t (:foreground "#c000ff"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:weight bold))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold))))
 '(font-lock-string-face ((t (:foreground "#008000"))))
 '(font-lock-type-face ((t (:foreground "#0000ff"))))
 '(font-lock-variable-name-face ((t (:foreground "#4040ff"))))
 '(fringe ((t (:background "#bfdfff"))))
 '(highlight ((((class color) (min-colors 89)) (:background "DodgerBlue4"))))
 '(info-header-node ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(info-header-xref ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(info-menu-header ((t (:weight bold :family "helv"))))
 '(info-node ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(info-xref ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(isearch ((t (:background "#000060" :foreground "#dfefff"))))
 '(lazy-highlight ((t (:background "#006000" :foreground "#dfefff"))))
 '(lazy-highlight ((t (:background "#006000" :foreground "#dfefff"))))
 '(match ((t (:background "#efdfff"))))
 '(minibuffer-prompt ((t (:foreground "#004080"))))
 '(mode-line ((((class color) (min-colors 89)) (:box (:line-width 1 :style released-button) :foreground "#004080" :background "#bfdfff"))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:foreground "blue4" :background nil :weight bold))))
 '(mode-line-inactive ((t (:foreground "#004080" :background "#9fcfff" :box (:line-width 1 :color "gray40")))))
 '(region ((t (:background "#bfffff"))))
 '(success ((t (:foreground "orange"))))
 '(warning ((t (:foreground "#ff00c0"))))
 '(default ((t (:background "#dfefff" :foreground "#004080")))))

(provide-theme 'light)
